---
description: Action that executes an arbitrary Linux command on the localhost.
enabled: true
entry_point: ''
name: local
parameters:
  cmd:
    description: Arbitrary Linux command to be executed on the local host.
    required: true
    type: string
  sudo:
    immutable: true
runner_type: "local-shell-cmd"
